function [final_array] = get_data_array(filename)

%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\eoand\Downloads\HW3-ASBR(1)\HW3-PA1\pa1-debug-a-empivot.txt
%
% Auto-generated by MATLAB on 21-Apr-2023 16:16:52

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "pa1debugaempivottxt"];
opts.VariableTypes = ["double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
data_from_file = readtable(filename, opts);

%% Convert to output type
final_array = table2array(data_from_file);

end 